spring:
  http:
    encoding:
      force: true
      charset: utf-8
  thymeleaf:
    encoding: UTF-8
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      enabled: true


server:
  port: 8888

config:
  jwt:
    secret: iwqjhda8232bjgh432[cicada-smile]
    expire: 3600
    header: token
  mysql:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.54.238.125:3306/study?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: denghang1989@163.com
  cache:
    driver-class-name: com.intersys.jdbc.CacheDriver
    url: jdbc:Cache://192.168.199.134:1972/dhc-app
    username: _system
    password: SYS

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.dhcc.cn.framework.mapper: DEBUG

constant:
  hospital: "宝安区人民医院"

wx:
  baseUrl: https://api.weixin.qq.com/
  templateId: 4tMLlBbhIP6NYMOHsrCrfZ5qjRWZWIDI-_MPEuWAWkw
  mp:
    app-id: wxefeac67815aedb20
    config-storage:
      type: memory
    token: 111
    secret: c4c38291d4cf613a8ef8d8c72a670488
    aes-key: 111